### ISSUE TITLE
👏h👏e👏r👏o👏k👏u👏

### ISSUE THREAD

**Issue by 8uX** [k6d/exeter#2]
add heroku support
![606115088235233280](https://user-images.githubusercontent.com/76086565/107864995-6829fd80-6e30-11eb-8b03-dd92ce8de813.gif)

**Comment by k6d** [comment]
soon™

**Comment by 8uX** [comment]
good

**Comment by 0lp** [comment]
> soon™

nicee

**Comment by k6d** [comment]
Repo unmaintained.
